plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 100

RSpec/SubjectStub:
  Enabled: false
