version: 2.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_ACCESS_TOKEN

jobs:
  bundle:
    parameters:
      ruby_version: { type: string }
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>
        <<: *docker-auth
        environment:
          BUNDLE_DEPLOYMENT: true
    steps:
      - checkout
      - restore_cache:
          key: gemfile-<< parameters.ruby_version >>-{{ checksum "Gemfile" }}
      - run: bundle install -j3
      - save_cache:
          key: gemfile-<< parameters.ruby_version >>-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle

  ruby:
    parameters:
      ruby_version: { type: string }
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>
        <<: *docker-auth
        environment:
          BUNDLE_DEPLOYMENT: true
    steps:
      - checkout
      - restore_cache:
          key: gemfile-<< parameters.ruby_version >>-{{ checksum "Gemfile" }}
      - run: gem install bundler:2.3.26
      - run: bundle check --path vendor/bundle
      - run: bundle exec rubocop
      - run: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out tmp/results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: tmp/results

workflows:
  version: 2
  build:
    jobs:
      - bundle:
          context: org-global
          matrix:
            parameters:
              ruby_version: ['2.7', '3.0']
      - ruby:
          context: org-global
          matrix:
            parameters:
              ruby_version: ['2.7', '3.0']
          requires:
            - bundle