version: 2.1

jobs:
  ruby3:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - restore_cache:
          key: gemfile-3-0-{{ checksum "Gemfile" }}-{{ checksum "selligent.gemspec" }}
      - run: gem install bundler:2.3.26
      - run: bundle config set --local path ./vendor/bundle
      - run: bundle config set --local frozen 'true'
      - run: bundle install -j3
      - save_cache:
          key: gemfile-3-0-{{ checksum "Gemfile" }}-{{ checksum "selligent.gemspec" }}
          paths:
            - vendor/bundle
      - run: bundle check --path vendor/bundle
      - run: bundle exec rubocop
      - run: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out tmp/results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: tmp/results


workflows:
  version: 2
  build:
    jobs:
      - ruby3
